# Product Manager - V2 Format (English)
version: 2

id: product-manager-en
name: Product Manager
description: Plan the production manifest and write micro-copy for the character
category: Agent
icon: Briefcase

# ============================================================================
# Input Form
# ============================================================================
input:
  - key: soulProfile
    label: Soul Profile
    type: string
    widget: json-input
    required: true
    connection: input
    placeholder: "Connect the 'Soul Profile' JSON output here"

  - key: productType
    label: Product Type
    type: string
    required: true
    connection: input

  - key: visualStyle
    label: Visual Style
    type: string
    required: true
    placeholder: "e.g. 3D Blind Box, Flat Vector, Cyberpunk..."
    connection: input

  - key: assetDefinitions
    label: Asset Definitions
    type: string
    widget: json-input
    required: true
    connection: input
    placeholder: "Pass asset definitions JSON (built with TableNode)"

# ============================================================================
# Model Requirements
# ============================================================================
model:
  category: llm
  capabilities:
    - chat
  defaultParams:
    temperature: 0.5
    maxTokens: 4096

# ============================================================================
# Prompt Templates
# ============================================================================
prompt:
  system: |
    You are the Product Manager (Agent C) of the Soulmate Protocol.
    Your goal is to bridge the "Soul" (Persona) and the "Body" (Visual Assets).

    【AVAILABLE ASSET TAXONOMY】
    The following asset types are available from the user-provided asset definitions:
    
    {{assetDefinitions}}
    
    Parse the id, label, family, and description fields from the JSON array.

    【YOUR TASK】
    1. **Analyze Strategy**: Look at the `Product Type` and `Soul Profile`.
    2. **Select Assets**: Choose 5-8 assets that are MOST relevant.
       - e.g., A "Weather App" needs `ui-kit-core` and `icon-set-variant`.
       - e.g., A "RPG Game" needs `character-turnaround` and `game-item-sheet`.
       - **Mandatory**: `character-main` (Key Visual) is mandatory for all projects.
    3. **Write Micro-Copy**:
       - For each chosen asset, write a short "Context Note" or "Micro-Copy" in the character's voice.
       - e.g., For a Loading State: "Hold tight! Charging up the sun..." (if they are a sun character).
    4. **Justify**: Briefly explain why this asset is needed.

    【OUTPUT FORMAT】
    Return a JSON Array representing the "Production Manifest".
    Format:
    [
      {
        "assetId": "ui-kit-core",  <-- MUST be exact ID from asset definitions
        "assetName": "Core UI Kit",
        "family": "grid",         <-- Asset family
        "priority": "High",
        "reason": "Essential for app user experience",
        "microCopy": "Thinking... processing... done!"
      },
      ...
    ]

    【CRITICAL】
    - Return ONLY valid JSON.
    - `assetId` MUST match the asset definitions EXACTLY.
    - Always include `character-main` as the first asset (priority: Critical).

  user: |
    Create a Production Manifest for:
    
    **Product Type:** {{productType}}
    **Visual Style:** {{visualStyle}}
    
    **Soul Profile:**
    {{soulProfile}}
    
    Select the best assets for this product and write creative micro-copy.

# ============================================================================
# Output Definition
# ============================================================================
output:
  format: json
  node: table
  title: "Production Manifest ({{count}} items)"
  collapsed: false
  config:
    columns:
      - key: assetId
        label: Asset ID
        type: string
        hidden: true
      - key: assetName
        label: Asset
        type: string
      - key: family
        label: Family
        type: string
      - key: priority
        label: Priority
        type: string
      - key: microCopy
        label: Copy / Context
        type: string
      - key: reason
        label: Rationale
        type: string

# ============================================================================
# Advanced Options
# ============================================================================
advanced:
  multiTurn: true

