// This file is auto-generated by Rust. Do not edit.

// NodeStatus
export type NodeStatus = "idle" | "processing" | "success" | "error" | "stale";

// SynniaProject
export type SynniaProject = { version: string, meta: ProjectMeta, viewport: Viewport, graph: Graph, settings: Record<string, any>, };

// SynniaNode
export type SynniaNode = { id: string, type: string, position: Position, width: number | null, height: number | null, data: AssetData, };

// SynniaEdge
export type SynniaEdge = { id: string, source: string, target: string, sourceHandle: string | null, targetHandle: string | null, type: string | null, label: string | null, animated: boolean | null, };

// AssetData
export type AssetData = { assetType: string, status: NodeStatus, hash: string | null, properties: Record<string, any>, provenance: Provenance | null, validationErrors: string[], };

// Provenance
export type Provenance = { recipeId: string, generatedAt: number, sources: Array<ProvenanceSource>, paramsSnapshot: Record<string, any>, };

// ProvenanceSource
export type ProvenanceSource = { nodeId: string, nodeVersion: number, nodeHash: string | null, slot: string | null, };

// AgentDefinition
export type AgentDefinition = { id: string, name: string, description: string | null, systemPrompt: string, inputSchema: string, outputConfig: string | null, isSystem: boolean, };

// ProjectMeta
export type ProjectMeta = { id: string, name: string, createdAt: string, updatedAt: string, thumbnail: string | null, description: string | null, author: string | null, };

// Viewport
export type Viewport = { x: number, y: number, zoom: number, };

// Graph
export type Graph = { nodes: Array<SynniaNode>, edges: Array<SynniaEdge>, };

// Position
export type Position = { x: number, y: number, };

