// This file is auto-generated by Rust. Do not edit.

// AssetType
export type AssetType = "Image" | "Text" | "Prompt" | "Link" | "Grid" | "Other";

// NodeStatus
export type NodeStatus = "Active" | "Outdated" | "Archived" | "Processing" | "Error";

// Project
export type Project = { id: string, name: string, created_at: string, path: string, };

// AssetNode
export type AssetNode = { id: string, project_id: string, type_: AssetType, status: NodeStatus, current_version_id: string | null, x: number, y: number, label: string | null, width: number | null, height: number | null, created_at: string, updated_at: string, };

// AssetVersion
export type AssetVersion = { id: string, asset_id: string, payload: string, meta: string | null, created_at: string, };

// Edge
export type Edge = { id: string, source_id: string, target_id: string, recipe: string | null, created_at: string, };

// AssetNodeWithData
export type AssetNodeWithData = { id: string, type_: AssetType, status: NodeStatus, x: number, y: number, label: string | null, width: number | null, height: number | null, payload: string | null, };

// AgentDefinition
export type AgentDefinition = { id: string, name: string, description: string | null, system_prompt: string, input_schema: string, output_config: string | null, is_system: boolean, };

