// This file is auto-generated by Rust (ts-rs). Do not edit.

// SynniaProject
export type SynniaProject = { version: string, meta: ProjectMeta, viewport: Viewport, graph: Graph, assets: Record<string, Asset>, settings: Record<string, any>, };

// ProjectMeta
export type ProjectMeta = { id: string, name: string, createdAt: string, updatedAt: string, thumbnail: string | null, description: string | null, author: string | null, };

// Viewport
export type Viewport = { x: number, y: number, zoom: number, };

// Graph
export type Graph = { nodes: Array<SynniaNode>, edges: Array<SynniaEdge>, };

// Asset
export type Asset = { id: string, type: string, content: any, metadata: AssetMetadata, };

// AssetMetadata
export type AssetMetadata = { name: string, createdAt: number, updatedAt: number, source: string | null, image: ImageAssetMetadata | null, text: TextAssetMetadata | null, extra: Record<string, any>, };

// SynniaNode
export type SynniaNode = { id: string, type: string, position: Position, width: number | null, height: number | null, parentId: string | null, extent: string | null, style: Record<string, any>, data: SynniaNodeData, };

// SynniaNodeData
export type SynniaNodeData = { title: string, assetId: string | null, isReference: boolean | null, collapsed: boolean | null, layoutMode: string | null, dockedTo: string | null, state: string | null, recipeId: string | null, };

// Position
export type Position = { x: number, y: number, };

// SynniaEdge
export type SynniaEdge = { id: string, source: string, target: string, sourceHandle: string | null, targetHandle: string | null, type: string | null, label: string | null, animated: boolean | null, };

// AgentDefinition
export type AgentDefinition = { id: string, name: string, description: string | null, systemPrompt: string, inputSchema: string, outputConfig: string | null, isSystem: boolean, };

