import { ProviderInfo } from './types';

export const PROVIDER_INFO: ProviderInfo[] = [
    // Cloud providers
    {
        key: 'openai',
        name: 'OpenAI',
        description: 'GPT-4o, DALL-E 3',
        type: 'cloud',
        placeholder: 'sk-...',
        defaultBaseUrl: 'https://api.openai.com/v1',
        requiresApiKey: true,
    },
    {
        key: 'anthropic',
        name: 'Anthropic',
        description: 'Claude 3.5 Sonnet',
        type: 'cloud',
        placeholder: 'sk-ant-...',
        defaultBaseUrl: 'https://api.anthropic.com/v1',
        requiresApiKey: true,
    },
    {
        key: 'google',
        name: 'Google AI',
        description: 'Gemini 2.0, Imagen',
        type: 'cloud',
        placeholder: 'AIza...',
        defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
        requiresApiKey: true,
    },
    {
        key: 'fal',
        name: 'FAL.ai',
        description: 'Flux, Nano Banana, Kling',
        type: 'cloud',
        placeholder: 'fal_...',
        defaultBaseUrl: 'https://fal.run',
        requiresApiKey: true,
    },
    {
        key: 'replicate',
        name: 'Replicate',
        description: 'Various open models',
        type: 'cloud',
        placeholder: 'r8_...',
        defaultBaseUrl: 'https://api.replicate.com/v1',
        requiresApiKey: true,
    },
    {
        key: 'deepseek',
        name: 'DeepSeek',
        description: 'DeepSeek V3',
        type: 'cloud',
        placeholder: 'sk-...',
        defaultBaseUrl: 'https://api.deepseek.com/v1',
        requiresApiKey: true,
    },
    {
        key: 'zhipu',
        name: 'Zhipu AI',
        description: 'GLM-4.7, GLM-4.6v',
        type: 'cloud',
        placeholder: 'your-zhipu-api-key',
        defaultBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        requiresApiKey: true,
    },
    {
        key: 'ppio',
        name: 'PPIO',
        description: 'PPIO Cloud GPU',
        type: 'cloud',
        placeholder: 'pp_...',
        defaultBaseUrl: 'https://api.ppinfra.com/v3/openai',
        requiresApiKey: true,
    },
    // Local providers
    {
        key: 'ollama',
        name: 'Ollama',
        description: 'Local LLM server',
        type: 'local',
        placeholder: 'Optional API key',
        defaultBaseUrl: 'http://localhost:11434',
        requiresApiKey: false,
    },
    {
        key: 'lmstudio',
        name: 'LM Studio',
        description: 'Local LLM server',
        type: 'local',
        placeholder: 'Optional API key',
        defaultBaseUrl: 'http://localhost:1234',
        requiresApiKey: false,
    },
    {
        key: 'comfyui',
        name: 'ComfyUI',
        description: 'Local image generation',
        type: 'local',
        placeholder: 'Optional API key',
        defaultBaseUrl: 'http://localhost:8188',
        requiresApiKey: false,
    },
    {
        key: 'g4f',
        name: 'GPT4Free',
        description: 'Local proxy (Gemini Imagen, etc.)',
        type: 'local',
        placeholder: 'Optional API key',
        defaultBaseUrl: 'http://localhost:8080',
        requiresApiKey: false,
    },
];
