/**
 * Handle Types and Semantics
 * 
 * Standardized handle definitions for Synnia nodes.
 * Nodes only declare semantics; styling is handled by NodePort component.
 */

// --- Semantic Categories ---
export enum HandleSemantic {
    DATA_IN = 'data-in',   // Data input port (left, gray→blue)
    DATA_OUT = 'data-out', // Data output port (right, green)
    ORIGIN = 'origin',     // Generated by whom (top, violet, non-interactive)
    PRODUCT = 'product',   // Generates what (bottom, purple, non-interactive)
}

// --- Standard Handle IDs ---
export const HANDLE_IDS = {
    ORIGIN: 'origin',   // Top ORIGIN handle
    PRODUCT: 'product', // Bottom PRODUCT handle
    OUTPUT: 'output',   // Node-level main data output
} as const;

// --- Style Configuration ---
export const HANDLE_CONFIG: Record<HandleSemantic, {
    position: 'top' | 'bottom' | 'left' | 'right';
    color: string;
    colorConnected?: string;
    disabled?: boolean;
}> = {
    [HandleSemantic.DATA_IN]: {
        position: 'left',
        color: 'bg-muted-foreground/40',
        colorConnected: 'bg-blue-500',
    },
    [HandleSemantic.DATA_OUT]: {
        position: 'right',
        color: 'bg-green-500',
    },
    [HandleSemantic.ORIGIN]: {
        position: 'top',
        color: 'bg-violet-500',
        disabled: true,
    },
    [HandleSemantic.PRODUCT]: {
        position: 'bottom',
        color: 'bg-purple-500',
        disabled: true,
    },
};
