// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentDefinition = { id: string, name: string, description: string | null, systemPrompt: string, inputSchema: string, outputConfig: string | null, isSystem: boolean, };
