// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentDefinition = { id: string, name: string, description: string | null, system_prompt: string, input_schema: string, output_config: string | null, is_system: boolean, };
