// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetMeta } from "./AssetMeta";

/**
 * Config for array assets (tables, selectors, galleries)
 */
export type ArrayAssetConfig = { schema: any[], meta: AssetMeta | null, itemSchema: any[], columns: any[], options: any[], mode: string | null, };
