// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Config for array assets (tables, selectors, galleries)
 */
export type ArrayAssetConfig = { itemSchema: any[], columns: any[], options: any[], mode: string | null, };
