// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetType } from "./AssetType";
import type { NodeStatus } from "./NodeStatus";

export type AssetNodeWithData = { id: string, type_: AssetType, status: NodeStatus, x: number, y: number, label: string | null, width: number | null, height: number | null, payload: string | null, };
