// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetSysMetadata } from "./AssetSysMetadata";
import type { ValueType } from "./ValueType";

/**
 * Unified Asset structure (Form-Centric Model)
 * Frontend uses valueType to determine the asset variant
 */
export type Asset = { id: string, valueType: ValueType, value: any, 
/**
 * Backend-generated metadata (dimensions, preview, length)
 */
valueMeta?: any, config?: any, sys: AssetSysMetadata, };
