// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * System metadata - tracks asset lifecycle
 */
export type AssetSysMetadata = { name: string, createdAt: number, updatedAt: number, source: string, };
