// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetMetadata } from "./AssetMetadata";

export type Asset = { id: string, type: string, content: any, metadata: AssetMetadata, };
