// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetSysMetadata } from "./AssetSysMetadata";
import type { ValueType } from "./ValueType";

/**
 * Unified Asset structure with discriminated union
 * Frontend uses valueType to determine the asset variant
 */
export type Asset = { id: string, valueType: ValueType, value: any, valueMeta: any, config: any, sys: AssetSysMetadata, };
