// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageAssetMetadata } from "./ImageAssetMetadata";
import type { TextAssetMetadata } from "./TextAssetMetadata";

export type AssetMetadata = { name: string, createdAt: number, updatedAt: number, source: string | null, image: ImageAssetMetadata | null, text: TextAssetMetadata | null, extra: Record<string, any>, };
