// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified Asset Metadata (replaces valueMeta)
 * Stored in config.meta
 */
export type AssetMeta = { preview: string | null, length: bigint | null, width: number | null, height: number | null, };
