// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeStatus } from "./NodeStatus";
import type { Provenance } from "./Provenance";

export type AssetData = { assetType: string, status: NodeStatus, hash: string | null, properties: Record<string, any>, provenance: Provenance | null, validationErrors: string[], };
