// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetType } from "./AssetType";
import type { NodeStatus } from "./NodeStatus";

export type AssetNode = { id: string, project_id: string, type_: AssetType, status: NodeStatus, current_version_id: string | null, x: number, y: number, label: string | null, width: number | null, height: number | null, created_at: string, updated_at: string, };
