// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Edge = { id: string, source_id: string, target_id: string, recipe: string | null, created_at: string, };
