// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionRun = { id: string, nodeId: string, recipeId?: string, startedAt: bigint, completedAt?: bigint, status: string, modelId?: string, durationMs?: bigint, tokenInput?: bigint, tokenOutput?: bigint, errorMessage?: string, };
