// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File tree node for Mini-IDE
 */
export type FileNode = { name: string, path: string, is_dir: boolean, children: Array<FileNode> | null, };
