// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type File = {
  id: string,
  mediaType: string,
  mimeType: string,
  source: string,
  storage: string,
  relativePath: string,
  originalName?: string,
  metadata?: any,
  variants?: any,
  createdAt: number,
  updatedAt: number,
};
