// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SynniaEdge } from "./SynniaEdge";
import type { SynniaNode } from "./SynniaNode";

export type Graph = { nodes: Array<SynniaNode>, edges: Array<SynniaEdge>, };
