// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata specific to image assets
 */
export type ImageAssetMetadata = { width: number, height: number, size: bigint | null, mimeType: string | null, thumbnail: string | null, hash: string | null, };
