// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Value metadata for image assets
 */
export type ImageValueMeta = { preview: string | null, width: number | null, height: number | null, };
