// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogEntry = { id: bigint, runId: string, timestamp: bigint, level: string, message: string, dataJson?: string, };
