// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectMeta = { id: string, name: string, createdAt: string, updatedAt: string, thumbnail: string | null, description: string | null, author: string | null, };
