// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider type identifiers.
 *
 * These correspond to the provider types used in the frontend model registry.
 * Exported to TypeScript via ts-rs for frontend type safety.
 */
export type ProviderType = "google" | "zhipu" | "openai" | "anthropic" | "deepseek" | "fal" | "ollama" | "lmstudio" | "g4f" | "modelscope" | "runninghub";
