// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProvenanceSource = { nodeId: string, nodeVersion: number, nodeHash: string | null, slot: string | null, };
