// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProvenanceSource } from "./ProvenanceSource";

export type Provenance = { recipeId: string, generatedAt: number, sources: Array<ProvenanceSource>, paramsSnapshot: Record<string, any>, };
