// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File system entry (folder or recipe)
 */
export type RecipeEntry = { "type": "folder", name: string, path: string, } | { "type": "recipe", id: string, path: string, name: string, description: string | null, author: string | null, icon: string | null, cover: string | null, };
