// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetMeta } from "./AssetMeta";

/**
 * Config for record assets (forms, text, image)
 */
export type RecordAssetConfig = { schema: any[], meta: AssetMeta | null, recipeId: string | null, modelConfig: any, chatContext: any, };
