// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunUpdate = { completedAt?: bigint, status?: string, durationMs?: bigint, tokenInput?: bigint, tokenOutput?: bigint, errorMessage?: string, };
