// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Asset } from "./Asset";
import type { Graph } from "./Graph";
import type { ProjectMeta } from "./ProjectMeta";
import type { Viewport } from "./Viewport";

/**
 * The root project structure.
 */
export type SynniaProject = { version: string, meta: ProjectMeta, viewport: Viewport, graph: Graph, 
/**
 * Central Asset Registry
 */
assets: Record<string, Asset>, settings: Record<string, any>, };
