// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetData } from "./AssetData";
import type { Position } from "./Position";

export type SynniaNode = { id: string, type: string, position: Position, width: number | null, height: number | null, data: AssetData, };
