// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { SynniaNodeData } from "./SynniaNodeData";

export type SynniaNode = { id: string, type: string, position: Position, width: number | null, height: number | null, parentId: string | null, extent: string | null, style: Record<string, any>, data: SynniaNodeData, };
