// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SynniaNodeData = { title: string, assetId: string | null, isReference: boolean | null, collapsed: boolean | null, layoutMode: string | null, dockedTo: string | null, state: string | null, other: Record<string, any>, };
