// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Config for text assets
 */
export type TextAssetConfig = { format: string | null, };
