// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata specific to text assets
 */
export type TextAssetMetadata = { length: bigint, encoding: string | null, };
