// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ValueType enum for Asset discrimination (Form-Centric Model)
 * - Record: Single structured form (TextNode, ImageNode, FormNode, RecipeNode)
 * - Array: Collection of records (TableNode, GalleryNode, SelectorNode)
 */
export type ValueType = "record" | "array";
