// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ValueType enum for Asset discrimination
 */
export type ValueType = "text" | "image" | "record" | "array";
