// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Viewport state (pan and zoom).
 */
export type Viewport = { x: number, y: number, zoom: number, };
